const DATA_KEY="tournament:data";
const SESSION_PREFIX="session:";
const SESSION_TTL=60*60*24*30;
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...extra}});
function cors(env,req){const origin=req.headers.get("Origin"),allowed=env.CORS_ORIGIN||"https://lashbury.co.uk";return origin===allowed?{"access-control-allow-origin":origin,"access-control-allow-credentials":"true","access-control-allow-headers":"content-type","access-control-allow-methods":"GET,POST,PUT,OPTIONS","vary":"Origin"}:{}}
async function hash(text){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function cookie(name,value,maxAge){return name+"="+value+"; Max-Age="+maxAge+"; Path=/; Secure; HttpOnly; SameSite=None"}
function getCookie(req,name){const raw=req.headers.get("Cookie")||"";for(const p of raw.split(";")){const i=p.trim().indexOf("=");if(i>0&&p.trim().slice(0,i)===name)return p.trim().slice(i+1)}return ""}
async function session(req,env){const token=getCookie(req,"lc_session");if(!token)return null;return await env.TOURNAMENT.get(SESSION_PREFIX+token,"json")}
async function requireSession(req,env,role){const s=await session(req,env);if(!s)return null;if(role==="owner"&&s.role!=="owner")return null;if(role==="admin"&&!["admin","owner"].includes(s.role))return null;return s}
async function login(req,env){const body=await req.json().catch(()=>({})),pin=String(body.pin||"");if(!pin||pin.length>128)return json({error:"Invalid PIN"},400);const hOwner=await hash("lc27:"+pin),hGuest=await hash("guest:"+pin);let role="";if(env.OWNER_PIN_HASH&&hOwner===env.OWNER_PIN_HASH)role="owner";else if(env.ADMIN_PIN_HASH&&hOwner===env.ADMIN_PIN_HASH)role="admin";else if(env.GUEST_PIN_HASH&&hGuest===env.GUEST_PIN_HASH)role="guest";if(!role)return json({error:"Wrong PIN"},401);const token=crypto.randomUUID()+crypto.randomUUID().replaceAll("-","");await env.TOURNAMENT.put(SESSION_PREFIX+token,JSON.stringify({role,created:Date.now()}),{expirationTtl:SESSION_TTL});return json({ok:true,role},200,{"set-cookie":cookie("lc_session",token,SESSION_TTL)})}
async function getData(req,env){const s=await requireSession(req,env,"guest");if(!s)return json({error:"Unauthorised"},401);const raw=await env.TOURNAMENT.get(DATA_KEY);if(!raw)return json({error:"Tournament data has not been imported yet"},503);return new Response(raw,{headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...cors(env,req)}})}
async function putData(req,env){const s=await requireSession(req,env,"admin");if(!s)return json({error:"Admin login required"},401);let parsed;try{parsed=await req.json()}catch{return json({error:"Invalid tournament data"},400)}if(!parsed||!Array.isArray(parsed.teams)||!Array.isArray(parsed.events))return json({error:"Invalid tournament data"},400);parsed.ts=Date.now();await env.TOURNAMENT.put(DATA_KEY,JSON.stringify(parsed));return json({ok:true,ts:parsed.ts},200,cors(env,req))}
export default{async fetch(req,env){const headers=cors(env,req);if(req.method==="OPTIONS")return new Response(null,{status:204,headers});const u=new URL(req.url);try{if(u.pathname==="/health"&&req.method==="GET")return json({ok:true},200,headers);if(u.pathname==="/auth/login"&&req.method==="POST"){const r=await login(req,env),h=new Headers(r.headers);Object.entries(headers).forEach(([k,v])=>h.set(k,v));return new Response(r.body,{status:r.status,headers:h})}if(u.pathname==="/auth/logout"&&req.method==="POST"){const token=getCookie(req,"lc_session");if(token)await env.TOURNAMENT.delete(SESSION_PREFIX+token);return json({ok:true},200,{...headers,"set-cookie":cookie("lc_session","",0)})}if(u.pathname==="/api/data"&&req.method==="GET")return getData(req,env);if(u.pathname==="/api/data"&&req.method==="PUT")return putData(req,env);if(u.pathname==="/api/session"&&req.method==="GET"){const s=await session(req,env);return json({authenticated:!!s,role:s?.role||null},200,headers)}return json({error:"Not found"},404,headers)}catch(e){return json({error:"Server error"},500,headers)}}};
